/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'ankurbrdwj' at '1/26/16 7:26 PM' with Gradle 2.9
 *
 * @author ankurbrdwj, @date 1/26/16 7:26 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
